/*
 Navicat Premium Data Transfer

 Source Server         : Mysql
 Source Server Type    : MySQL
 Source Server Version : 80028
 Source Host           : localhost:3306
 Source Schema         : nacos

 Target Server Type    : MySQL
 Target Server Version : 80028
 File Encoding         : 65001

 Date: 10/05/2023 14:26:51
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for config_info
-- ----------------------------
DROP TABLE IF EXISTS `config_info`;
CREATE TABLE `config_info`  (
  `id` bigint(0) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  `c_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `c_use` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `effect` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `c_schema` text CHARACTER SET utf8 COLLATE utf8_bin NULL,
  `encrypted_data_key` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '秘钥',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfo_datagrouptenant`(`data_id`, `group_id`, `tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_info
-- ----------------------------
INSERT INTO `config_info` VALUES (12, 'service-gateway-dev.properties', 'DEFAULT_GROUP', '#网关发现配置\nspring.cloud.gateway.discovery.locator.enabled=true\n\n#设置路由id\nspring.cloud.gateway.routes[0].id=service-acl\n#设置路由的uri   lb://nacos注册服务名称\nspring.cloud.gateway.routes[0].uri=lb://service-acl\n#设置路由断言,代理servicerId为auth-service的/auth/路径\nspring.cloud.gateway.routes[0].predicates= Path=/*/acl/**\n\n#配置service-edu服务\nspring.cloud.gateway.routes[1].id=service-edu\nspring.cloud.gateway.routes[1].uri=lb://service-edu\nspring.cloud.gateway.routes[1].predicates= Path=/eduservice/**\n\n#service-ucenter\nspring.cloud.gateway.routes[2].id=service-ucenter\nspring.cloud.gateway.routes[2].uri=lb://service-ucenter\nspring.cloud.gateway.routes[2].predicates= Path=/educenter/**\n\n#service-cms\nspring.cloud.gateway.routes[3].id=service-cms\nspring.cloud.gateway.routes[3].uri=lb://service-cms\nspring.cloud.gateway.routes[3].predicates= Path=/cmsservice/**\n\nspring.cloud.gateway.routes[4].id=service-msm\nspring.cloud.gateway.routes[4].uri=lb://service-msm\nspring.cloud.gateway.routes[4].predicates= Path=/edumsm/**\n\nspring.cloud.gateway.routes[5].id=service-order\nspring.cloud.gateway.routes[5].uri=lb://service-order\nspring.cloud.gateway.routes[5].predicates= Path=/eduorder/**\n\nspring.cloud.gateway.routes[6].id=service-oss\nspring.cloud.gateway.routes[6].uri=lb://service-oss\nspring.cloud.gateway.routes[6].predicates= Path=/eduoss/**\n\nspring.cloud.gateway.routes[7].id=service-statistics\nspring.cloud.gateway.routes[7].uri=lb://service-statistics\nspring.cloud.gateway.routes[7].predicates= Path=/staservice/**\n\nspring.cloud.gateway.routes[8].id=service-vod\nspring.cloud.gateway.routes[8].uri=lb://service-vod\nspring.cloud.gateway.routes[8].predicates= Path=/eduvod/**\n\nspring.cloud.gateway.routes[9].id=service-edu\nspring.cloud.gateway.routes[9].uri=lb://service-edu\nspring.cloud.gateway.routes[9].predicates= Path=/eduuser/**\n\nspring.cloud.gateway.default-filters=DedupeResponseHeader=Vary Access-Control-Allow-Credentials Access-Control-Allow-Origin', 'da9544fd8a5d95b83c635b05fec59add', '2023-05-10 03:03:58', '2023-05-10 03:11:22', 'nacos', '0:0:0:0:0:0:0:1', '', '', '网关', '', '', 'properties', '', '');
INSERT INTO `config_info` VALUES (15, 'service-cms-dev.properties', 'DEFAULT_GROUP', '# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#json日期\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mapper路径\r\nmybatis-plus.mapper-locations=classpath:com/hhz/servicecms/mapper/xml/*.xml\r\n\r\n#redis配置Linux的ip\r\nspring.redis.host=192.168.10.100\r\nspring.redis.port=6379\r\nspring.redis.database= 0\r\nspring.redis.timeout=1800000\r\n#redis配置\r\nspring.redis.lettuce.pool.max-active=20\r\nspring.redis.lettuce.pool.max-wait=-1\r\nspring.redis.lettuce.pool.max-idle=5\r\nspring.redis.lettuce.pool.min-idle=0\r\n\r\n#mybatis控制台打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl', '9f32cda6c78075ce23aad93ce62fd3c3', '2023-05-10 03:37:15', '2023-05-10 03:37:15', NULL, '0:0:0:0:0:0:0:1', '', '', '幻灯片', NULL, NULL, 'properties', NULL, '');
INSERT INTO `config_info` VALUES (16, 'service-edu-dev.properties', 'DEFAULT_GROUP', '# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#json日期格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mapper路径格式\r\nmybatis-plus.mapper-locations=classpath:com/hhz/serviceedu/mapper/xml/*.xml\r\n\r\n#熔断使用\r\n#feign.hystrix.enabled=true\r\n#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=6000\r\n\r\n#日志等级\r\nlogging.level.root=INFO\r\n#mybatis控制打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl\r\n\r\n\r\n# es 服务地址\r\nspring.elasticsearch.rest.uris=http://localhost:9200\r\nspring.elasticsearch.rest.username=\r\nspring.elasticsearch.rest.password=\r\n', 'a2e31bd5ce6514f320c1d43430daef99', '2023-05-10 03:37:58', '2023-05-10 03:37:58', NULL, '0:0:0:0:0:0:0:1', '', '', '教育服务', NULL, NULL, 'properties', NULL, '');
INSERT INTO `config_info` VALUES (17, 'service-msm-dev.properties', 'DEFAULT_GROUP', '# mysql配置\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\nspring.datasource.username=root\nspring.datasource.password=123456\n\n#redis配置Linux的ip\nspring.redis.host=localhost\nspring.redis.port=6379\nspring.redis.database= 0\nspring.redis.timeout=1800000\n#redis配置\nspring.redis.lettuce.pool.max-active=20\nspring.redis.lettuce.pool.max-wait=-1\nspring.redis.lettuce.pool.max-idle=5\nspring.redis.lettuce.pool.min-idle=0\n\n# ali服务\naliyun.msm.keyId=\naliyun.msm.keySecret=\naliyun.msm.region=cn-shanghai\naliyun.msm.signName=\naliyun.msm.templateCode=\n\n#json日期格式\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\nspring.jackson.time-zone=GMT+8\n\n#mybatis控制台打印格式\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl\n', '7adf00e14376af39f275401da6385d56', '2023-05-10 03:38:39', '2023-05-10 03:38:57', 'nacos', '0:0:0:0:0:0:0:1', '', '', '短信服务', '', '', 'properties', '', '');
INSERT INTO `config_info` VALUES (19, 'service-order-dev.properties', 'DEFAULT_GROUP', '# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#json日期格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mapper路径\r\nmybatis-plus.mapper-locations=classpath:com/hhz/serviceorder/mapper/xml/*.xml\r\n\r\n#mybatis控制台打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl\r\n\r\n#熔断启动\r\n#feign.hystrix.enabled=true\r\n#最大超时时间\r\n#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=3000', '5f854bf1772af994054c6d61160d4170', '2023-05-10 03:39:35', '2023-05-10 03:39:35', NULL, '0:0:0:0:0:0:0:1', '', '', '订单', NULL, NULL, 'properties', NULL, '');
INSERT INTO `config_info` VALUES (20, 'service-oss-dev.properties', 'DEFAULT_GROUP', '#阿里云 OSS\n#oss配置\naliyun.oss.file.endpoint=\naliyun.oss.file.keyid=\naliyun.oss.file.keysecret=\n#bucket名\naliyun.oss.file.bucketname=yuhaiedu', 'e41ec8ce3a80b38a40db7e7b6485c162', '2023-05-10 03:40:02', '2023-05-10 06:25:58', 'nacos', '0:0:0:0:0:0:0:1', '', '', 'oss', '', '', 'properties', '', '');
INSERT INTO `config_info` VALUES (21, 'service-statistics-dev.properties', 'DEFAULT_GROUP', '# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#json日期格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mapper路径\r\nmybatis-plus.mapper-locations=classpath:com/hhz/statistics/mapper/xml/*.xml\r\n\r\n#mybatis控制台打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl', '787b4d3adae48edc82e688d6dde61962', '2023-05-10 03:40:29', '2023-05-10 03:40:29', NULL, '0:0:0:0:0:0:0:1', '', '', NULL, NULL, NULL, 'properties', NULL, '');
INSERT INTO `config_info` VALUES (22, 'service-ucenter-dev.properties', 'DEFAULT_GROUP', '# mysql\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#redis使用Linux配置ip\r\nspring.redis.host=localhost\r\nspring.redis.port=6379\r\n#redis配置\r\nspring.redis.database= 0\r\nspring.redis.timeout=1800000\r\nspring.redis.lettuce.pool.max-active=20\r\nspring.redis.lettuce.pool.max-wait=-1\r\nspring.redis.lettuce.pool.max-idle=5\r\nspring.redis.lettuce.pool.min-idle=0\r\n\r\n#微信支付接口()\r\n# appid\r\nwx.open.app_id=wxed9954c01bb89b47\r\n# appsecret\r\nwx.open.app_secret=a7482517235173ddb4083788de60b90e\r\n# url\r\nwx.open.redirect_url=http://guli.shop/api/ucenter/wx/callback\r\n\r\n#支付宝支付\r\nalipay.APP_ID=\r\nalipay.APP_PRIVATE_KEY=\r\nalipay.ALIPAY_PUBLIC_KEY=\r\nalipay.GATEWAY_URL=\r\n\r\n\r\n#json时间格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mapper路径\r\nmybatis-plus.mapper-locations=classpath:com/hhz/ucenter/mapper/xml/*.xml\r\n\r\n#mybatis控制台打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl', '8e13bbcf2c551a124343e3de4dc31185', '2023-05-10 03:41:10', '2023-05-10 03:41:10', NULL, '0:0:0:0:0:0:0:1', '', '', NULL, NULL, NULL, 'properties', NULL, '');
INSERT INTO `config_info` VALUES (23, 'service-vod-dev.properties', 'DEFAULT_GROUP', '# vod\n#accesskey\naliyun.vod.file.keyid=\naliyun.vod.file.keysecret=\n\n# 单个文件最大上传大小\nspring.servlet.multipart.max-file-size=1024MB\n# 请求数10M\nspring.servlet.multipart.max-request-size=1024MB\n', 'd0125d10cefdd73f272d646c38a1a26d', '2023-05-10 03:41:33', '2023-05-10 06:26:31', 'nacos', '0:0:0:0:0:0:0:1', '', '', '', '', '', 'properties', '', '');
INSERT INTO `config_info` VALUES (24, 'service-acl-dev.properties', 'DEFAULT_GROUP', '# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#json日期格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#Redis使用Linux配置的ip\r\nspring.redis.host=127.0.0.1\r\nspring.redis.port=6379\r\nspring.redis.database= 0\r\nspring.redis.timeout=1800000\r\n#redis配置\r\nspring.redis.lettuce.pool.max-active=20\r\nspring.redis.lettuce.pool.max-wait=-1\r\nspring.redis.lettuce.pool.max-idle=5\r\nspring.redis.lettuce.pool.min-idle=0\r\n\r\n#mapper路径\r\nmybatis-plus.mapper-locations=classpath:com/hhz/serviceacl/mapper/xml/*.xml\r\n\r\n#mybatis配置控制台打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl', 'f680ecd1e119724c62587319a2589670', '2023-05-10 03:42:02', '2023-05-10 03:42:02', NULL, '0:0:0:0:0:0:0:1', '', '', NULL, NULL, NULL, 'properties', NULL, '');
INSERT INTO `config_info` VALUES (29, 'canal-client-dev.properties', 'DEFAULT_GROUP', '# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#canal 服务地址\r\ncanalClient.host=127.0.0.1\r\ncanalClient.port=11111\r\ncanalClient.destination=example\r\ncanalClient.username=\r\ncanalClient.password=\r\ncanalClient.batchsize=1000\r\n\r\n\r\n# es 服务地址\r\nspring.elasticsearch.rest.uris=http://localhost:9200\r\nspring.elasticsearch.rest.username=\r\nspring.elasticsearch.rest.password=', '50b0456963173fd193a10d0d283e66f9', '2023-05-10 06:05:27', '2023-05-10 06:05:27', NULL, '0:0:0:0:0:0:0:1', '', '', '数据同步', NULL, NULL, 'properties', NULL, '');

-- ----------------------------
-- Table structure for config_info_aggr
-- ----------------------------
DROP TABLE IF EXISTS `config_info_aggr`;
CREATE TABLE `config_info_aggr`  (
  `id` bigint(0) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `datum_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'datum_id',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '内容',
  `gmt_modified` datetime(0) NOT NULL COMMENT '修改时间',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfoaggr_datagrouptenantdatum`(`data_id`, `group_id`, `tenant_id`, `datum_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '增加租户字段' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_info_aggr
-- ----------------------------

-- ----------------------------
-- Table structure for config_info_beta
-- ----------------------------
DROP TABLE IF EXISTS `config_info_beta`;
CREATE TABLE `config_info_beta`  (
  `id` bigint(0) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `beta_ips` varchar(1024) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'betaIps',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  `encrypted_data_key` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '秘钥',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfobeta_datagrouptenant`(`data_id`, `group_id`, `tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info_beta' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_info_beta
-- ----------------------------

-- ----------------------------
-- Table structure for config_info_tag
-- ----------------------------
DROP TABLE IF EXISTS `config_info_tag`;
CREATE TABLE `config_info_tag`  (
  `id` bigint(0) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `tag_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_id',
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'content',
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'md5',
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '修改时间',
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL COMMENT 'source user',
  `src_ip` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'source ip',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_configinfotag_datagrouptenanttag`(`data_id`, `group_id`, `tenant_id`, `tag_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_info_tag' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_info_tag
-- ----------------------------

-- ----------------------------
-- Table structure for config_tags_relation
-- ----------------------------
DROP TABLE IF EXISTS `config_tags_relation`;
CREATE TABLE `config_tags_relation`  (
  `id` bigint(0) NOT NULL COMMENT 'id',
  `tag_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'tag_name',
  `tag_type` varchar(64) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'tag_type',
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'data_id',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'group_id',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `nid` bigint(0) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`nid`) USING BTREE,
  UNIQUE INDEX `uk_configtagrelation_configidtag`(`id`, `tag_name`, `tag_type`) USING BTREE,
  INDEX `idx_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'config_tag_relation' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of config_tags_relation
-- ----------------------------

-- ----------------------------
-- Table structure for group_capacity
-- ----------------------------
DROP TABLE IF EXISTS `group_capacity`;
CREATE TABLE `group_capacity`  (
  `id` bigint(0) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Group ID，空字符表示整个集群',
  `quota` int(0) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配额，0表示使用默认值',
  `usage` int(0) UNSIGNED NOT NULL DEFAULT 0 COMMENT '使用量',
  `max_size` int(0) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int(0) UNSIGNED NOT NULL DEFAULT 0 COMMENT '聚合子配置最大个数，，0表示使用默认值',
  `max_aggr_size` int(0) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int(0) UNSIGNED NOT NULL DEFAULT 0 COMMENT '最大变更历史数量',
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_group_id`(`group_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '集群、各Group容量信息表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of group_capacity
-- ----------------------------

-- ----------------------------
-- Table structure for his_config_info
-- ----------------------------
DROP TABLE IF EXISTS `his_config_info`;
CREATE TABLE `his_config_info`  (
  `id` bigint(0) UNSIGNED NOT NULL,
  `nid` bigint(0) UNSIGNED NOT NULL AUTO_INCREMENT,
  `data_id` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `group_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `app_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'app_name',
  `content` longtext CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `md5` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  `src_user` text CHARACTER SET utf8 COLLATE utf8_bin NULL,
  `src_ip` varchar(50) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `op_type` char(10) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL,
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT '租户字段',
  `encrypted_data_key` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '秘钥',
  PRIMARY KEY (`nid`) USING BTREE,
  INDEX `idx_gmt_create`(`gmt_create`) USING BTREE,
  INDEX `idx_gmt_modified`(`gmt_modified`) USING BTREE,
  INDEX `idx_did`(`data_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '多租户改造' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of his_config_info
-- ----------------------------
INSERT INTO `his_config_info` VALUES (0, 1, 'service-gateway', 'DEFAULT_GROUP', '', '# 端口号\r\nserver.port=8222\r\n#服务发现名\r\nspring.application.name=service-gateway\r\n# nacos配置\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\n\r\n#网关发现配置\r\nspring.cloud.gateway.discovery.locator.enabled=true\r\n\r\n#设置路由id\r\nspring.cloud.gateway.routes[0].id=service-acl\r\n#设置路由的uri   lb://nacos注册服务名称\r\nspring.cloud.gateway.routes[0].uri=lb://service-acl\r\n#设置路由断言,代理servicerId为auth-service的/auth/路径\r\nspring.cloud.gateway.routes[0].predicates= Path=/*/acl/**\r\n\r\n#配置service-edu服务\r\nspring.cloud.gateway.routes[1].id=service-edu\r\nspring.cloud.gateway.routes[1].uri=lb://service-edu\r\nspring.cloud.gateway.routes[1].predicates= Path=/eduservice/**\r\n\r\n#service-ucenter\r\nspring.cloud.gateway.routes[2].id=service-ucenter\r\nspring.cloud.gateway.routes[2].uri=lb://service-ucenter\r\nspring.cloud.gateway.routes[2].predicates= Path=/educenter/**\r\n\r\n#service-cms\r\nspring.cloud.gateway.routes[3].id=service-cms\r\nspring.cloud.gateway.routes[3].uri=lb://service-cms\r\nspring.cloud.gateway.routes[3].predicates= Path=/cmsservice/**\r\n\r\nspring.cloud.gateway.routes[4].id=service-msm\r\nspring.cloud.gateway.routes[4].uri=lb://service-msm\r\nspring.cloud.gateway.routes[4].predicates= Path=/edumsm/**\r\n\r\nspring.cloud.gateway.routes[5].id=service-order\r\nspring.cloud.gateway.routes[5].uri=lb://service-order\r\nspring.cloud.gateway.routes[5].predicates= Path=/eduorder/**\r\n\r\nspring.cloud.gateway.routes[6].id=service-oss\r\nspring.cloud.gateway.routes[6].uri=lb://service-oss\r\nspring.cloud.gateway.routes[6].predicates= Path=/eduoss/**\r\n\r\nspring.cloud.gateway.routes[7].id=service-statistics\r\nspring.cloud.gateway.routes[7].uri=lb://service-statistics\r\nspring.cloud.gateway.routes[7].predicates= Path=/staservice/**\r\n\r\nspring.cloud.gateway.routes[8].id=service-vod\r\nspring.cloud.gateway.routes[8].uri=lb://service-vod\r\nspring.cloud.gateway.routes[8].predicates= Path=/eduvod/**\r\n\r\nspring.cloud.gateway.routes[9].id=service-edu\r\nspring.cloud.gateway.routes[9].uri=lb://service-edu\r\nspring.cloud.gateway.routes[9].predicates= Path=/eduuser/**\r\n\r\nspring.cloud.gateway.default-filters=DedupeResponseHeader=Vary Access-Control-Allow-Credentials Access-Control-Allow-Origin', 'f1c3d95dc64595628cd50b053852ad19', '2023-05-10 10:30:15', '2023-05-10 02:30:16', NULL, '0:0:0:0:0:0:0:1', 'I', '', '');
INSERT INTO `his_config_info` VALUES (0, 2, 'service-acl', 'DEFAULT_GROUP', '', '#端口号\r\nserver.port=8009\r\n#服务发现名\r\nspring.application.name=service-acl\r\n\r\n# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#json日期格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#Redis使用Linux配置的ip\r\nspring.redis.host=127.0.0.1\r\nspring.redis.port=6379\r\nspring.redis.database= 0\r\nspring.redis.timeout=1800000\r\n#redis配置\r\nspring.redis.lettuce.pool.max-active=20\r\nspring.redis.lettuce.pool.max-wait=-1\r\nspring.redis.lettuce.pool.max-idle=5\r\nspring.redis.lettuce.pool.min-idle=0\r\n\r\n#mapper路径\r\nmybatis-plus.mapper-locations=classpath:com/hhz/serviceacl/mapper/xml/*.xml\r\n\r\n# nacos配置\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\n\r\n#mybatis配置控制台打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl', '77f8a545cc3b5d49a8c47945a22642ba', '2023-05-10 10:30:42', '2023-05-10 02:30:42', NULL, '0:0:0:0:0:0:0:1', 'I', '', '');
INSERT INTO `his_config_info` VALUES (0, 3, 'service-cms', 'DEFAULT_GROUP', '', '#端口号\r\nserver.port=8004\r\n#服务发现名\r\nspring.application.name=service-cms\r\n\r\n# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#json日期\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mapper路径\r\nmybatis-plus.mapper-locations=classpath:com/hhz/servicecms/mapper/xml/*.xml\r\n\r\n#redis配置Linux的ip\r\nspring.redis.host=192.168.10.100\r\nspring.redis.port=6379\r\nspring.redis.database= 0\r\nspring.redis.timeout=1800000\r\n#redis配置\r\nspring.redis.lettuce.pool.max-active=20\r\nspring.redis.lettuce.pool.max-wait=-1\r\nspring.redis.lettuce.pool.max-idle=5\r\nspring.redis.lettuce.pool.min-idle=0\r\n\r\n#mybatis控制台打印格式\r\n#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl\r\n\r\n# nacos配置\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848', '1a0ce1e688f4fb7ded31ffb53a20eb9c', '2023-05-10 10:31:02', '2023-05-10 02:31:03', NULL, '0:0:0:0:0:0:0:1', 'I', '', '');
INSERT INTO `his_config_info` VALUES (0, 4, 'service-edu', 'DEFAULT_GROUP', '', '#端口号\r\nserver.port=8001\r\n#服务发现名\r\nspring.application.name=service-edu\r\n\r\nspring.profiles.active=dev\r\n\r\n# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#json日期格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mapper路径格式\r\nmybatis-plus.mapper-locations=classpath:com/hhz/serviceedu/mapper/xml/*.xml\r\n\r\n# nacos\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\n\r\n\r\n\r\n#熔断使用\r\n#feign.hystrix.enabled=true\r\n#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=6000\r\n\r\n#日志等级\r\nlogging.level.root=INFO\r\n#mybatis控制打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl\r\n\r\n\r\n# es 服务地址\r\nspring.elasticsearch.rest.uris=http://localhost:9200\r\nspring.elasticsearch.rest.username=\r\nspring.elasticsearch.rest.password=\r\n', '65a52226faa54bb29d7decf45ee0f38a', '2023-05-10 10:32:07', '2023-05-10 02:32:08', NULL, '0:0:0:0:0:0:0:1', 'I', '', '');
INSERT INTO `his_config_info` VALUES (0, 5, 'service-msm', 'DEFAULT_GROUP', '', '#端口号\r\nserver.port=8005\r\n#服务发现名\r\nspring.application.name=service-msm\r\n\r\n# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n\r\n# nacos\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\n\r\n#redis配置Linux的ip\r\nspring.redis.host=localhost\r\nspring.redis.port=6379\r\nspring.redis.database= 0\r\nspring.redis.timeout=1800000\r\n#redis配置\r\nspring.redis.lettuce.pool.max-active=20\r\nspring.redis.lettuce.pool.max-wait=-1\r\nspring.redis.lettuce.pool.max-idle=5\r\nspring.redis.lettuce.pool.min-idle=0\r\n\r\n# ali服务\r\naliyun.msm.keyId=LTAI5tK5JkFaffQhZ2TZT5D8\r\naliyun.msm.keySecret=XzzWyEXkbOnOGfmfhYiEbYofdxHwZ5\r\naliyun.msm.region=cn-shanghai\r\naliyun.msm.signName=黄海钊个人网站\r\naliyun.msm.templateCode=SMS_273060065\r\n\r\n#json日期格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mybatis控制台打印格式\r\n#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl\r\n', '20611bfa8ea6d100cc6de1d927870544', '2023-05-10 10:32:31', '2023-05-10 02:32:31', NULL, '0:0:0:0:0:0:0:1', 'I', '', '');
INSERT INTO `his_config_info` VALUES (0, 6, 'service-order', 'DEFAULT_GROUP', '', '#端口号\r\nserver.port=8007\r\n#服务发现名\r\nspring.application.name=service-order\r\n\r\n# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#json日期格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mapper路径\r\nmybatis-plus.mapper-locations=classpath:com/hhz/serviceorder/mapper/xml/*.xml\r\n\r\n#mybatis控制台打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl\r\n\r\n# nacos配置\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\n\r\n#熔断启动\r\n#feign.hystrix.enabled=true\r\n#最大超时时间\r\n#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=3000', 'a16ef97a6be7cd755592ab0d495e7e11', '2023-05-10 10:32:48', '2023-05-10 02:32:49', NULL, '0:0:0:0:0:0:0:1', 'I', '', '');
INSERT INTO `his_config_info` VALUES (0, 7, 'service-oss', 'DEFAULT_GROUP', '', '#端口号\r\nserver.port=8002\r\n#服务发现名\r\nspring.application.name=service-oss\r\n\r\nspring.profiles.active=dev\r\n\r\n# nacos配置\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\n\r\n#阿里云 OSS\r\n#oss配置\r\naliyun.oss.file.endpoint=oss-cn-hongkong.aliyuncs.com\r\naliyun.oss.file.keyid=\r\naliyun.oss.file.keysecret=\r\n#bucket名\r\naliyun.oss.file.bucketname=yuhaiedu\r\n', '54c04333e41df49a835c89fc67f00bae', '2023-05-10 10:33:10', '2023-05-10 02:33:11', NULL, '0:0:0:0:0:0:0:1', 'I', '', '');
INSERT INTO `his_config_info` VALUES (0, 8, 'service-statistics', 'DEFAULT_GROUP', '', '#端口号\r\nserver.port=8008\r\n#服务发现名\r\nspring.application.name=service-statistics\r\n\r\n# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#json日期格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mapper路径\r\nmybatis-plus.mapper-locations=classpath:com/hhz/statistics/mapper/xml/*.xml\r\n\r\n#mybatis控制台打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl\r\n\r\n# nacos配置\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848', 'ef7d30f8d940ea36f25fe50f57ebb23c', '2023-05-10 10:33:31', '2023-05-10 02:33:32', NULL, '0:0:0:0:0:0:0:1', 'I', '', '');
INSERT INTO `his_config_info` VALUES (0, 9, 'service-ucenter', 'DEFAULT_GROUP', '', '#端口号\r\nserver.port=8150\r\n#服务发现名\r\nspring.application.name=service-ucenter\r\n\r\n# mysql\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#redis使用Linux配置ip\r\nspring.redis.host=localhost\r\nspring.redis.port=6379\r\n#redis配置\r\nspring.redis.database= 0\r\nspring.redis.timeout=1800000\r\nspring.redis.lettuce.pool.max-active=20\r\nspring.redis.lettuce.pool.max-wait=-1\r\nspring.redis.lettuce.pool.max-idle=5\r\nspring.redis.lettuce.pool.min-idle=0\r\n\r\n#微信支付接口()\r\n# appid\r\nwx.open.app_id=wxed9954c01bb89b47\r\n# appsecret\r\nwx.open.app_secret=a7482517235173ddb4083788de60b90e\r\n# url\r\nwx.open.redirect_url=http://guli.shop/api/ucenter/wx/callback\r\n\r\n#支付宝支付\r\nalipay.APP_ID=\r\nalipay.APP_PRIVATE_KEY=\r\nalipay.ALIPAY_PUBLIC_KEY=\r\nalipay.GATEWAY_URL=\r\n\r\n\r\n#json时间格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mapper路径\r\nmybatis-plus.mapper-locations=classpath:com/hhz/ucenter/mapper/xml/*.xml\r\n\r\n# nacos映射\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\n\r\n#mybatis控制台打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl', '9957ff423ad8cdea4cc526b30f566367', '2023-05-10 10:34:13', '2023-05-10 02:34:14', NULL, '0:0:0:0:0:0:0:1', 'I', '', '');
INSERT INTO `his_config_info` VALUES (0, 10, 'service-vod', 'DEFAULT_GROUP', '', '#端口号\r\nserver.port=8003\r\n#服务发现名\r\nspring.application.name=service-vod\r\n\r\n#使用配置文件\r\nspring.profiles.active=dev\r\n\r\n# nacos配置\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\n\r\n# vod\r\n#accesskey\r\naliyun.vod.file.keyid=\r\naliyun.vod.file.keysecret=\r\n\r\n# 单个文件最大上传大小\r\nspring.servlet.multipart.max-file-size=1024MB\r\n# 请求数10M\r\nspring.servlet.multipart.max-request-size=1024MB\r\n', '44fd2d898de204701044fba141efbead', '2023-05-10 10:34:34', '2023-05-10 02:34:35', NULL, '0:0:0:0:0:0:0:1', 'I', '', '');
INSERT INTO `his_config_info` VALUES (1, 11, 'service-gateway', 'DEFAULT_GROUP', '', '# 端口号\r\nserver.port=8222\r\n#服务发现名\r\nspring.application.name=service-gateway\r\n# nacos配置\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\n\r\n#网关发现配置\r\nspring.cloud.gateway.discovery.locator.enabled=true\r\n\r\n#设置路由id\r\nspring.cloud.gateway.routes[0].id=service-acl\r\n#设置路由的uri   lb://nacos注册服务名称\r\nspring.cloud.gateway.routes[0].uri=lb://service-acl\r\n#设置路由断言,代理servicerId为auth-service的/auth/路径\r\nspring.cloud.gateway.routes[0].predicates= Path=/*/acl/**\r\n\r\n#配置service-edu服务\r\nspring.cloud.gateway.routes[1].id=service-edu\r\nspring.cloud.gateway.routes[1].uri=lb://service-edu\r\nspring.cloud.gateway.routes[1].predicates= Path=/eduservice/**\r\n\r\n#service-ucenter\r\nspring.cloud.gateway.routes[2].id=service-ucenter\r\nspring.cloud.gateway.routes[2].uri=lb://service-ucenter\r\nspring.cloud.gateway.routes[2].predicates= Path=/educenter/**\r\n\r\n#service-cms\r\nspring.cloud.gateway.routes[3].id=service-cms\r\nspring.cloud.gateway.routes[3].uri=lb://service-cms\r\nspring.cloud.gateway.routes[3].predicates= Path=/cmsservice/**\r\n\r\nspring.cloud.gateway.routes[4].id=service-msm\r\nspring.cloud.gateway.routes[4].uri=lb://service-msm\r\nspring.cloud.gateway.routes[4].predicates= Path=/edumsm/**\r\n\r\nspring.cloud.gateway.routes[5].id=service-order\r\nspring.cloud.gateway.routes[5].uri=lb://service-order\r\nspring.cloud.gateway.routes[5].predicates= Path=/eduorder/**\r\n\r\nspring.cloud.gateway.routes[6].id=service-oss\r\nspring.cloud.gateway.routes[6].uri=lb://service-oss\r\nspring.cloud.gateway.routes[6].predicates= Path=/eduoss/**\r\n\r\nspring.cloud.gateway.routes[7].id=service-statistics\r\nspring.cloud.gateway.routes[7].uri=lb://service-statistics\r\nspring.cloud.gateway.routes[7].predicates= Path=/staservice/**\r\n\r\nspring.cloud.gateway.routes[8].id=service-vod\r\nspring.cloud.gateway.routes[8].uri=lb://service-vod\r\nspring.cloud.gateway.routes[8].predicates= Path=/eduvod/**\r\n\r\nspring.cloud.gateway.routes[9].id=service-edu\r\nspring.cloud.gateway.routes[9].uri=lb://service-edu\r\nspring.cloud.gateway.routes[9].predicates= Path=/eduuser/**\r\n\r\nspring.cloud.gateway.default-filters=DedupeResponseHeader=Vary Access-Control-Allow-Credentials Access-Control-Allow-Origin', 'f1c3d95dc64595628cd50b053852ad19', '2023-05-10 11:01:43', '2023-05-10 03:01:44', NULL, '0:0:0:0:0:0:0:1', 'D', '', '');
INSERT INTO `his_config_info` VALUES (2, 12, 'service-acl', 'DEFAULT_GROUP', '', '#端口号\r\nserver.port=8009\r\n#服务发现名\r\nspring.application.name=service-acl\r\n\r\n# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#json日期格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#Redis使用Linux配置的ip\r\nspring.redis.host=127.0.0.1\r\nspring.redis.port=6379\r\nspring.redis.database= 0\r\nspring.redis.timeout=1800000\r\n#redis配置\r\nspring.redis.lettuce.pool.max-active=20\r\nspring.redis.lettuce.pool.max-wait=-1\r\nspring.redis.lettuce.pool.max-idle=5\r\nspring.redis.lettuce.pool.min-idle=0\r\n\r\n#mapper路径\r\nmybatis-plus.mapper-locations=classpath:com/hhz/serviceacl/mapper/xml/*.xml\r\n\r\n# nacos配置\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\n\r\n#mybatis配置控制台打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl', '77f8a545cc3b5d49a8c47945a22642ba', '2023-05-10 11:01:43', '2023-05-10 03:01:44', NULL, '0:0:0:0:0:0:0:1', 'D', '', '');
INSERT INTO `his_config_info` VALUES (3, 13, 'service-cms', 'DEFAULT_GROUP', '', '#端口号\r\nserver.port=8004\r\n#服务发现名\r\nspring.application.name=service-cms\r\n\r\n# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#json日期\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mapper路径\r\nmybatis-plus.mapper-locations=classpath:com/hhz/servicecms/mapper/xml/*.xml\r\n\r\n#redis配置Linux的ip\r\nspring.redis.host=192.168.10.100\r\nspring.redis.port=6379\r\nspring.redis.database= 0\r\nspring.redis.timeout=1800000\r\n#redis配置\r\nspring.redis.lettuce.pool.max-active=20\r\nspring.redis.lettuce.pool.max-wait=-1\r\nspring.redis.lettuce.pool.max-idle=5\r\nspring.redis.lettuce.pool.min-idle=0\r\n\r\n#mybatis控制台打印格式\r\n#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl\r\n\r\n# nacos配置\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848', '1a0ce1e688f4fb7ded31ffb53a20eb9c', '2023-05-10 11:01:43', '2023-05-10 03:01:44', NULL, '0:0:0:0:0:0:0:1', 'D', '', '');
INSERT INTO `his_config_info` VALUES (4, 14, 'service-edu', 'DEFAULT_GROUP', '', '#端口号\r\nserver.port=8001\r\n#服务发现名\r\nspring.application.name=service-edu\r\n\r\nspring.profiles.active=dev\r\n\r\n# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#json日期格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mapper路径格式\r\nmybatis-plus.mapper-locations=classpath:com/hhz/serviceedu/mapper/xml/*.xml\r\n\r\n# nacos\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\n\r\n\r\n\r\n#熔断使用\r\n#feign.hystrix.enabled=true\r\n#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=6000\r\n\r\n#日志等级\r\nlogging.level.root=INFO\r\n#mybatis控制打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl\r\n\r\n\r\n# es 服务地址\r\nspring.elasticsearch.rest.uris=http://localhost:9200\r\nspring.elasticsearch.rest.username=\r\nspring.elasticsearch.rest.password=\r\n', '65a52226faa54bb29d7decf45ee0f38a', '2023-05-10 11:01:43', '2023-05-10 03:01:44', NULL, '0:0:0:0:0:0:0:1', 'D', '', '');
INSERT INTO `his_config_info` VALUES (5, 15, 'service-msm', 'DEFAULT_GROUP', '', '#端口号\r\nserver.port=8005\r\n#服务发现名\r\nspring.application.name=service-msm\r\n\r\n# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n\r\n# nacos\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\n\r\n#redis配置Linux的ip\r\nspring.redis.host=localhost\r\nspring.redis.port=6379\r\nspring.redis.database= 0\r\nspring.redis.timeout=1800000\r\n#redis配置\r\nspring.redis.lettuce.pool.max-active=20\r\nspring.redis.lettuce.pool.max-wait=-1\r\nspring.redis.lettuce.pool.max-idle=5\r\nspring.redis.lettuce.pool.min-idle=0\r\n\r\n# ali服务\r\naliyun.msm.keyId=LTAI5tK5JkFaffQhZ2TZT5D8\r\naliyun.msm.keySecret=XzzWyEXkbOnOGfmfhYiEbYofdxHwZ5\r\naliyun.msm.region=cn-shanghai\r\naliyun.msm.signName=黄海钊个人网站\r\naliyun.msm.templateCode=SMS_273060065\r\n\r\n#json日期格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mybatis控制台打印格式\r\n#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl\r\n', '20611bfa8ea6d100cc6de1d927870544', '2023-05-10 11:01:43', '2023-05-10 03:01:44', NULL, '0:0:0:0:0:0:0:1', 'D', '', '');
INSERT INTO `his_config_info` VALUES (6, 16, 'service-order', 'DEFAULT_GROUP', '', '#端口号\r\nserver.port=8007\r\n#服务发现名\r\nspring.application.name=service-order\r\n\r\n# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#json日期格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mapper路径\r\nmybatis-plus.mapper-locations=classpath:com/hhz/serviceorder/mapper/xml/*.xml\r\n\r\n#mybatis控制台打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl\r\n\r\n# nacos配置\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\n\r\n#熔断启动\r\n#feign.hystrix.enabled=true\r\n#最大超时时间\r\n#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=3000', 'a16ef97a6be7cd755592ab0d495e7e11', '2023-05-10 11:01:43', '2023-05-10 03:01:44', NULL, '0:0:0:0:0:0:0:1', 'D', '', '');
INSERT INTO `his_config_info` VALUES (7, 17, 'service-oss', 'DEFAULT_GROUP', '', '#端口号\r\nserver.port=8002\r\n#服务发现名\r\nspring.application.name=service-oss\r\n\r\nspring.profiles.active=dev\r\n\r\n# nacos配置\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\n\r\n#阿里云 OSS\r\n#oss配置\r\naliyun.oss.file.endpoint=oss-cn-hongkong.aliyuncs.com\r\naliyun.oss.file.keyid=\r\naliyun.oss.file.keysecret=\r\n#bucket名\r\naliyun.oss.file.bucketname=yuhaiedu\r\n', '54c04333e41df49a835c89fc67f00bae', '2023-05-10 11:01:43', '2023-05-10 03:01:44', NULL, '0:0:0:0:0:0:0:1', 'D', '', '');
INSERT INTO `his_config_info` VALUES (8, 18, 'service-statistics', 'DEFAULT_GROUP', '', '#端口号\r\nserver.port=8008\r\n#服务发现名\r\nspring.application.name=service-statistics\r\n\r\n# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#json日期格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mapper路径\r\nmybatis-plus.mapper-locations=classpath:com/hhz/statistics/mapper/xml/*.xml\r\n\r\n#mybatis控制台打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl\r\n\r\n# nacos配置\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848', 'ef7d30f8d940ea36f25fe50f57ebb23c', '2023-05-10 11:01:43', '2023-05-10 03:01:44', NULL, '0:0:0:0:0:0:0:1', 'D', '', '');
INSERT INTO `his_config_info` VALUES (9, 19, 'service-ucenter', 'DEFAULT_GROUP', '', '#端口号\r\nserver.port=8150\r\n#服务发现名\r\nspring.application.name=service-ucenter\r\n\r\n# mysql\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#redis使用Linux配置ip\r\nspring.redis.host=localhost\r\nspring.redis.port=6379\r\n#redis配置\r\nspring.redis.database= 0\r\nspring.redis.timeout=1800000\r\nspring.redis.lettuce.pool.max-active=20\r\nspring.redis.lettuce.pool.max-wait=-1\r\nspring.redis.lettuce.pool.max-idle=5\r\nspring.redis.lettuce.pool.min-idle=0\r\n\r\n#微信支付接口()\r\n# appid\r\nwx.open.app_id=wxed9954c01bb89b47\r\n# appsecret\r\nwx.open.app_secret=a7482517235173ddb4083788de60b90e\r\n# url\r\nwx.open.redirect_url=http://guli.shop/api/ucenter/wx/callback\r\n\r\n#支付宝支付\r\nalipay.APP_ID=\r\nalipay.APP_PRIVATE_KEY=\r\nalipay.ALIPAY_PUBLIC_KEY=\r\nalipay.GATEWAY_URL=\r\n\r\n\r\n#json时间格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mapper路径\r\nmybatis-plus.mapper-locations=classpath:com/hhz/ucenter/mapper/xml/*.xml\r\n\r\n# nacos映射\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\n\r\n#mybatis控制台打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl', '9957ff423ad8cdea4cc526b30f566367', '2023-05-10 11:01:43', '2023-05-10 03:01:44', NULL, '0:0:0:0:0:0:0:1', 'D', '', '');
INSERT INTO `his_config_info` VALUES (10, 20, 'service-vod', 'DEFAULT_GROUP', '', '#端口号\r\nserver.port=8003\r\n#服务发现名\r\nspring.application.name=service-vod\r\n\r\n#使用配置文件\r\nspring.profiles.active=dev\r\n\r\n# nacos配置\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\n\r\n# vod\r\n#accesskey\r\naliyun.vod.file.keyid=\r\naliyun.vod.file.keysecret=\r\n\r\n# 单个文件最大上传大小\r\nspring.servlet.multipart.max-file-size=1024MB\r\n# 请求数10M\r\nspring.servlet.multipart.max-request-size=1024MB\r\n', '44fd2d898de204701044fba141efbead', '2023-05-10 11:01:43', '2023-05-10 03:01:44', NULL, '0:0:0:0:0:0:0:1', 'D', '', '');
INSERT INTO `his_config_info` VALUES (0, 21, 'service-gateway-dev', 'DEFAULT_GROUP', '', '# 端口号\r\nserver.port=8222\r\n#服务发现名\r\nspring.application.name=service-gateway\r\n\r\n#网关发现配置\r\nspring.cloud.gateway.discovery.locator.enabled=true\r\n\r\n#设置路由id\r\nspring.cloud.gateway.routes[0].id=service-acl\r\n#设置路由的uri   lb://nacos注册服务名称\r\nspring.cloud.gateway.routes[0].uri=lb://service-acl\r\n#设置路由断言,代理servicerId为auth-service的/auth/路径\r\nspring.cloud.gateway.routes[0].predicates= Path=/*/acl/**\r\n\r\n#配置service-edu服务\r\nspring.cloud.gateway.routes[1].id=service-edu\r\nspring.cloud.gateway.routes[1].uri=lb://service-edu\r\nspring.cloud.gateway.routes[1].predicates= Path=/eduservice/**\r\n\r\n#service-ucenter\r\nspring.cloud.gateway.routes[2].id=service-ucenter\r\nspring.cloud.gateway.routes[2].uri=lb://service-ucenter\r\nspring.cloud.gateway.routes[2].predicates= Path=/educenter/**\r\n\r\n#service-cms\r\nspring.cloud.gateway.routes[3].id=service-cms\r\nspring.cloud.gateway.routes[3].uri=lb://service-cms\r\nspring.cloud.gateway.routes[3].predicates= Path=/cmsservice/**\r\n\r\nspring.cloud.gateway.routes[4].id=service-msm\r\nspring.cloud.gateway.routes[4].uri=lb://service-msm\r\nspring.cloud.gateway.routes[4].predicates= Path=/edumsm/**\r\n\r\nspring.cloud.gateway.routes[5].id=service-order\r\nspring.cloud.gateway.routes[5].uri=lb://service-order\r\nspring.cloud.gateway.routes[5].predicates= Path=/eduorder/**\r\n\r\nspring.cloud.gateway.routes[6].id=service-oss\r\nspring.cloud.gateway.routes[6].uri=lb://service-oss\r\nspring.cloud.gateway.routes[6].predicates= Path=/eduoss/**\r\n\r\nspring.cloud.gateway.routes[7].id=service-statistics\r\nspring.cloud.gateway.routes[7].uri=lb://service-statistics\r\nspring.cloud.gateway.routes[7].predicates= Path=/staservice/**\r\n\r\nspring.cloud.gateway.routes[8].id=service-vod\r\nspring.cloud.gateway.routes[8].uri=lb://service-vod\r\nspring.cloud.gateway.routes[8].predicates= Path=/eduvod/**\r\n\r\nspring.cloud.gateway.routes[9].id=service-edu\r\nspring.cloud.gateway.routes[9].uri=lb://service-edu\r\nspring.cloud.gateway.routes[9].predicates= Path=/eduuser/**\r\n\r\nspring.cloud.gateway.default-filters=DedupeResponseHeader=Vary Access-Control-Allow-Credentials Access-Control-Allow-Origin', '3fa78b16a97c7661ca37f516f2c741d1', '2023-05-10 11:02:51', '2023-05-10 03:02:52', NULL, '0:0:0:0:0:0:0:1', 'I', '', '');
INSERT INTO `his_config_info` VALUES (11, 22, 'service-gateway-dev', 'DEFAULT_GROUP', '', '# 端口号\r\nserver.port=8222\r\n#服务发现名\r\nspring.application.name=service-gateway\r\n\r\n#网关发现配置\r\nspring.cloud.gateway.discovery.locator.enabled=true\r\n\r\n#设置路由id\r\nspring.cloud.gateway.routes[0].id=service-acl\r\n#设置路由的uri   lb://nacos注册服务名称\r\nspring.cloud.gateway.routes[0].uri=lb://service-acl\r\n#设置路由断言,代理servicerId为auth-service的/auth/路径\r\nspring.cloud.gateway.routes[0].predicates= Path=/*/acl/**\r\n\r\n#配置service-edu服务\r\nspring.cloud.gateway.routes[1].id=service-edu\r\nspring.cloud.gateway.routes[1].uri=lb://service-edu\r\nspring.cloud.gateway.routes[1].predicates= Path=/eduservice/**\r\n\r\n#service-ucenter\r\nspring.cloud.gateway.routes[2].id=service-ucenter\r\nspring.cloud.gateway.routes[2].uri=lb://service-ucenter\r\nspring.cloud.gateway.routes[2].predicates= Path=/educenter/**\r\n\r\n#service-cms\r\nspring.cloud.gateway.routes[3].id=service-cms\r\nspring.cloud.gateway.routes[3].uri=lb://service-cms\r\nspring.cloud.gateway.routes[3].predicates= Path=/cmsservice/**\r\n\r\nspring.cloud.gateway.routes[4].id=service-msm\r\nspring.cloud.gateway.routes[4].uri=lb://service-msm\r\nspring.cloud.gateway.routes[4].predicates= Path=/edumsm/**\r\n\r\nspring.cloud.gateway.routes[5].id=service-order\r\nspring.cloud.gateway.routes[5].uri=lb://service-order\r\nspring.cloud.gateway.routes[5].predicates= Path=/eduorder/**\r\n\r\nspring.cloud.gateway.routes[6].id=service-oss\r\nspring.cloud.gateway.routes[6].uri=lb://service-oss\r\nspring.cloud.gateway.routes[6].predicates= Path=/eduoss/**\r\n\r\nspring.cloud.gateway.routes[7].id=service-statistics\r\nspring.cloud.gateway.routes[7].uri=lb://service-statistics\r\nspring.cloud.gateway.routes[7].predicates= Path=/staservice/**\r\n\r\nspring.cloud.gateway.routes[8].id=service-vod\r\nspring.cloud.gateway.routes[8].uri=lb://service-vod\r\nspring.cloud.gateway.routes[8].predicates= Path=/eduvod/**\r\n\r\nspring.cloud.gateway.routes[9].id=service-edu\r\nspring.cloud.gateway.routes[9].uri=lb://service-edu\r\nspring.cloud.gateway.routes[9].predicates= Path=/eduuser/**\r\n\r\nspring.cloud.gateway.default-filters=DedupeResponseHeader=Vary Access-Control-Allow-Credentials Access-Control-Allow-Origin', '3fa78b16a97c7661ca37f516f2c741d1', '2023-05-10 11:03:32', '2023-05-10 03:03:32', NULL, '0:0:0:0:0:0:0:1', 'D', '', '');
INSERT INTO `his_config_info` VALUES (0, 23, 'service-gateway-dev.properties', 'DEFAULT_GROUP', '', '# 端口号\r\nserver.port=8222\r\n#服务发现名\r\nspring.application.name=service-gateway\r\n\r\n#网关发现配置\r\nspring.cloud.gateway.discovery.locator.enabled=true\r\n\r\n#设置路由id\r\nspring.cloud.gateway.routes[0].id=service-acl\r\n#设置路由的uri   lb://nacos注册服务名称\r\nspring.cloud.gateway.routes[0].uri=lb://service-acl\r\n#设置路由断言,代理servicerId为auth-service的/auth/路径\r\nspring.cloud.gateway.routes[0].predicates= Path=/*/acl/**\r\n\r\n#配置service-edu服务\r\nspring.cloud.gateway.routes[1].id=service-edu\r\nspring.cloud.gateway.routes[1].uri=lb://service-edu\r\nspring.cloud.gateway.routes[1].predicates= Path=/eduservice/**\r\n\r\n#service-ucenter\r\nspring.cloud.gateway.routes[2].id=service-ucenter\r\nspring.cloud.gateway.routes[2].uri=lb://service-ucenter\r\nspring.cloud.gateway.routes[2].predicates= Path=/educenter/**\r\n\r\n#service-cms\r\nspring.cloud.gateway.routes[3].id=service-cms\r\nspring.cloud.gateway.routes[3].uri=lb://service-cms\r\nspring.cloud.gateway.routes[3].predicates= Path=/cmsservice/**\r\n\r\nspring.cloud.gateway.routes[4].id=service-msm\r\nspring.cloud.gateway.routes[4].uri=lb://service-msm\r\nspring.cloud.gateway.routes[4].predicates= Path=/edumsm/**\r\n\r\nspring.cloud.gateway.routes[5].id=service-order\r\nspring.cloud.gateway.routes[5].uri=lb://service-order\r\nspring.cloud.gateway.routes[5].predicates= Path=/eduorder/**\r\n\r\nspring.cloud.gateway.routes[6].id=service-oss\r\nspring.cloud.gateway.routes[6].uri=lb://service-oss\r\nspring.cloud.gateway.routes[6].predicates= Path=/eduoss/**\r\n\r\nspring.cloud.gateway.routes[7].id=service-statistics\r\nspring.cloud.gateway.routes[7].uri=lb://service-statistics\r\nspring.cloud.gateway.routes[7].predicates= Path=/staservice/**\r\n\r\nspring.cloud.gateway.routes[8].id=service-vod\r\nspring.cloud.gateway.routes[8].uri=lb://service-vod\r\nspring.cloud.gateway.routes[8].predicates= Path=/eduvod/**\r\n\r\nspring.cloud.gateway.routes[9].id=service-edu\r\nspring.cloud.gateway.routes[9].uri=lb://service-edu\r\nspring.cloud.gateway.routes[9].predicates= Path=/eduuser/**\r\n\r\nspring.cloud.gateway.default-filters=DedupeResponseHeader=Vary Access-Control-Allow-Credentials Access-Control-Allow-Origin', '3fa78b16a97c7661ca37f516f2c741d1', '2023-05-10 11:03:58', '2023-05-10 03:03:58', NULL, '0:0:0:0:0:0:0:1', 'I', '', '');
INSERT INTO `his_config_info` VALUES (12, 24, 'service-gateway-dev.properties', 'DEFAULT_GROUP', '', '# 端口号\r\nserver.port=8222\r\n#服务发现名\r\nspring.application.name=service-gateway\r\n\r\n#网关发现配置\r\nspring.cloud.gateway.discovery.locator.enabled=true\r\n\r\n#设置路由id\r\nspring.cloud.gateway.routes[0].id=service-acl\r\n#设置路由的uri   lb://nacos注册服务名称\r\nspring.cloud.gateway.routes[0].uri=lb://service-acl\r\n#设置路由断言,代理servicerId为auth-service的/auth/路径\r\nspring.cloud.gateway.routes[0].predicates= Path=/*/acl/**\r\n\r\n#配置service-edu服务\r\nspring.cloud.gateway.routes[1].id=service-edu\r\nspring.cloud.gateway.routes[1].uri=lb://service-edu\r\nspring.cloud.gateway.routes[1].predicates= Path=/eduservice/**\r\n\r\n#service-ucenter\r\nspring.cloud.gateway.routes[2].id=service-ucenter\r\nspring.cloud.gateway.routes[2].uri=lb://service-ucenter\r\nspring.cloud.gateway.routes[2].predicates= Path=/educenter/**\r\n\r\n#service-cms\r\nspring.cloud.gateway.routes[3].id=service-cms\r\nspring.cloud.gateway.routes[3].uri=lb://service-cms\r\nspring.cloud.gateway.routes[3].predicates= Path=/cmsservice/**\r\n\r\nspring.cloud.gateway.routes[4].id=service-msm\r\nspring.cloud.gateway.routes[4].uri=lb://service-msm\r\nspring.cloud.gateway.routes[4].predicates= Path=/edumsm/**\r\n\r\nspring.cloud.gateway.routes[5].id=service-order\r\nspring.cloud.gateway.routes[5].uri=lb://service-order\r\nspring.cloud.gateway.routes[5].predicates= Path=/eduorder/**\r\n\r\nspring.cloud.gateway.routes[6].id=service-oss\r\nspring.cloud.gateway.routes[6].uri=lb://service-oss\r\nspring.cloud.gateway.routes[6].predicates= Path=/eduoss/**\r\n\r\nspring.cloud.gateway.routes[7].id=service-statistics\r\nspring.cloud.gateway.routes[7].uri=lb://service-statistics\r\nspring.cloud.gateway.routes[7].predicates= Path=/staservice/**\r\n\r\nspring.cloud.gateway.routes[8].id=service-vod\r\nspring.cloud.gateway.routes[8].uri=lb://service-vod\r\nspring.cloud.gateway.routes[8].predicates= Path=/eduvod/**\r\n\r\nspring.cloud.gateway.routes[9].id=service-edu\r\nspring.cloud.gateway.routes[9].uri=lb://service-edu\r\nspring.cloud.gateway.routes[9].predicates= Path=/eduuser/**\r\n\r\nspring.cloud.gateway.default-filters=DedupeResponseHeader=Vary Access-Control-Allow-Credentials Access-Control-Allow-Origin', '3fa78b16a97c7661ca37f516f2c741d1', '2023-05-10 11:07:02', '2023-05-10 03:07:02', 'nacos', '0:0:0:0:0:0:0:1', 'U', '', '');
INSERT INTO `his_config_info` VALUES (12, 25, 'service-gateway-dev.properties', 'DEFAULT_GROUP', '', '# 端口号\nserver.port=8222\n#服务发现名\nspring.application.name=service-gateway\n\n#网关发现配置\nspring.cloud.gateway.discovery.locator.enabled=true\n\n#设置路由id\nspring.cloud.gateway.routes[0].id=service-acl\n#设置路由的uri   lb://nacos注册服务名称\nspring.cloud.gateway.routes[0].uri=lb://service-acl\n#设置路由断言,代理servicerId为auth-service的/auth/路径\nspring.cloud.gateway.routes[0].predicates= Path=/*/acl/**\n\n#配置service-edu服务\nspring.cloud.gateway.routes[1].id=service-edu\nspring.cloud.gateway.routes[1].uri=lb://service-edu\nspring.cloud.gateway.routes[1].predicates= Path=/eduservice/**\n\n#service-ucenter\nspring.cloud.gateway.routes[2].id=service-ucenter\nspring.cloud.gateway.routes[2].uri=lb://service-ucenter\nspring.cloud.gateway.routes[2].predicates= Path=/educenter/**\n\n#service-cms\nspring.cloud.gateway.routes[3].id=service-cms\nspring.cloud.gateway.routes[3].uri=lb://service-cms\nspring.cloud.gateway.routes[3].predicates= Path=/cmsservice/**\n\nspring.cloud.gateway.routes[4].id=service-msm\nspring.cloud.gateway.routes[4].uri=lb://service-msm\nspring.cloud.gateway.routes[4].predicates= Path=/edumsm/**\n\nspring.cloud.gateway.routes[5].id=service-order\nspring.cloud.gateway.routes[5].uri=lb://service-order\nspring.cloud.gateway.routes[5].predicates= Path=/eduorder/**\n\nspring.cloud.gateway.routes[6].id=service-oss\nspring.cloud.gateway.routes[6].uri=lb://service-oss\nspring.cloud.gateway.routes[6].predicates= Path=/eduoss/**\n\nspring.cloud.gateway.routes[7].id=service-statistics\nspring.cloud.gateway.routes[7].uri=lb://service-statistics\nspring.cloud.gateway.routes[7].predicates= Path=/staservice/**\n\nspring.cloud.gateway.routes[8].id=service-vod\nspring.cloud.gateway.routes[8].uri=lb://service-vod\nspring.cloud.gateway.routes[8].predicates= Path=/eduvod/**\n\nspring.cloud.gateway.routes[9].id=service-edu\nspring.cloud.gateway.routes[9].uri=lb://service-edu\nspring.cloud.gateway.routes[9].predicates= Path=/eduuser/**\n\nspring.cloud.gateway.default-filters=DedupeResponseHeader=Vary Access-Control-Allow-Credentials Access-Control-Allow-Origin', '90c8a80e732735c9e20915eaa7f68cfd', '2023-05-10 11:11:22', '2023-05-10 03:11:22', 'nacos', '0:0:0:0:0:0:0:1', 'U', '', '');
INSERT INTO `his_config_info` VALUES (0, 26, 'service-cms-dev.properties', 'DEFAULT_GROUP', '', '# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#json日期\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mapper路径\r\nmybatis-plus.mapper-locations=classpath:com/hhz/servicecms/mapper/xml/*.xml\r\n\r\n#redis配置Linux的ip\r\nspring.redis.host=192.168.10.100\r\nspring.redis.port=6379\r\nspring.redis.database= 0\r\nspring.redis.timeout=1800000\r\n#redis配置\r\nspring.redis.lettuce.pool.max-active=20\r\nspring.redis.lettuce.pool.max-wait=-1\r\nspring.redis.lettuce.pool.max-idle=5\r\nspring.redis.lettuce.pool.min-idle=0\r\n\r\n#mybatis控制台打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl', '9f32cda6c78075ce23aad93ce62fd3c3', '2023-05-10 11:37:14', '2023-05-10 03:37:15', NULL, '0:0:0:0:0:0:0:1', 'I', '', '');
INSERT INTO `his_config_info` VALUES (0, 27, 'service-edu-dev.properties', 'DEFAULT_GROUP', '', '# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#json日期格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mapper路径格式\r\nmybatis-plus.mapper-locations=classpath:com/hhz/serviceedu/mapper/xml/*.xml\r\n\r\n#熔断使用\r\n#feign.hystrix.enabled=true\r\n#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=6000\r\n\r\n#日志等级\r\nlogging.level.root=INFO\r\n#mybatis控制打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl\r\n\r\n\r\n# es 服务地址\r\nspring.elasticsearch.rest.uris=http://localhost:9200\r\nspring.elasticsearch.rest.username=\r\nspring.elasticsearch.rest.password=\r\n', 'a2e31bd5ce6514f320c1d43430daef99', '2023-05-10 11:37:57', '2023-05-10 03:37:58', NULL, '0:0:0:0:0:0:0:1', 'I', '', '');
INSERT INTO `his_config_info` VALUES (0, 28, 'service-msm-dev.properties', 'DEFAULT_GROUP', '', '# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#redis配置Linux的ip\r\nspring.redis.host=localhost\r\nspring.redis.port=6379\r\nspring.redis.database= 0\r\nspring.redis.timeout=1800000\r\n#redis配置\r\nspring.redis.lettuce.pool.max-active=20\r\nspring.redis.lettuce.pool.max-wait=-1\r\nspring.redis.lettuce.pool.max-idle=5\r\nspring.redis.lettuce.pool.min-idle=0\r\n\r\n# ali服务\r\naliyun.msm.keyId=LTAI5tK5JkFaffQhZ2TZT5D8\r\naliyun.msm.keySecret=XzzWyEXkbOnOGfmfhYiEbYofdxHwZ5\r\naliyun.msm.region=cn-shanghai\r\naliyun.msm.signName=黄海钊个人网站\r\naliyun.msm.templateCode=SMS_273060065\r\n\r\n#json日期格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mybatis控制台打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl\r\n', '80e4bb9f89bd683b1a851a23a8c17379', '2023-05-10 11:38:39', '2023-05-10 03:38:39', NULL, '0:0:0:0:0:0:0:1', 'I', '', '');
INSERT INTO `his_config_info` VALUES (17, 29, 'service-msm-dev.properties', 'DEFAULT_GROUP', '', '# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#redis配置Linux的ip\r\nspring.redis.host=localhost\r\nspring.redis.port=6379\r\nspring.redis.database= 0\r\nspring.redis.timeout=1800000\r\n#redis配置\r\nspring.redis.lettuce.pool.max-active=20\r\nspring.redis.lettuce.pool.max-wait=-1\r\nspring.redis.lettuce.pool.max-idle=5\r\nspring.redis.lettuce.pool.min-idle=0\r\n\r\n# ali服务\r\naliyun.msm.keyId=LTAI5tK5JkFaffQhZ2TZT5D8\r\naliyun.msm.keySecret=XzzWyEXkbOnOGfmfhYiEbYofdxHwZ5\r\naliyun.msm.region=cn-shanghai\r\naliyun.msm.signName=黄海钊个人网站\r\naliyun.msm.templateCode=SMS_273060065\r\n\r\n#json日期格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mybatis控制台打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl\r\n', '80e4bb9f89bd683b1a851a23a8c17379', '2023-05-10 11:38:56', '2023-05-10 03:38:57', 'nacos', '0:0:0:0:0:0:0:1', 'U', '', '');
INSERT INTO `his_config_info` VALUES (0, 30, 'service-order-dev.properties', 'DEFAULT_GROUP', '', '# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#json日期格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mapper路径\r\nmybatis-plus.mapper-locations=classpath:com/hhz/serviceorder/mapper/xml/*.xml\r\n\r\n#mybatis控制台打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl\r\n\r\n#熔断启动\r\n#feign.hystrix.enabled=true\r\n#最大超时时间\r\n#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds=3000', '5f854bf1772af994054c6d61160d4170', '2023-05-10 11:39:34', '2023-05-10 03:39:35', NULL, '0:0:0:0:0:0:0:1', 'I', '', '');
INSERT INTO `his_config_info` VALUES (0, 31, 'service-oss-dev.properties', 'DEFAULT_GROUP', '', '#阿里云 OSS\r\n#oss配置\r\naliyun.oss.file.endpoint=oss-cn-hongkong.aliyuncs.com\r\naliyun.oss.file.keyid=\r\naliyun.oss.file.keysecret=\r\n#bucket名\r\naliyun.oss.file.bucketname=yuhaiedu\r\n', 'e0b1ee8a69539b8dabf55275e0c296e5', '2023-05-10 11:40:02', '2023-05-10 03:40:02', NULL, '0:0:0:0:0:0:0:1', 'I', '', '');
INSERT INTO `his_config_info` VALUES (0, 32, 'service-statistics-dev.properties', 'DEFAULT_GROUP', '', '# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#json日期格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mapper路径\r\nmybatis-plus.mapper-locations=classpath:com/hhz/statistics/mapper/xml/*.xml\r\n\r\n#mybatis控制台打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl', '787b4d3adae48edc82e688d6dde61962', '2023-05-10 11:40:28', '2023-05-10 03:40:29', NULL, '0:0:0:0:0:0:0:1', 'I', '', '');
INSERT INTO `his_config_info` VALUES (0, 33, 'service-ucenter-dev.properties', 'DEFAULT_GROUP', '', '# mysql\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#redis使用Linux配置ip\r\nspring.redis.host=localhost\r\nspring.redis.port=6379\r\n#redis配置\r\nspring.redis.database= 0\r\nspring.redis.timeout=1800000\r\nspring.redis.lettuce.pool.max-active=20\r\nspring.redis.lettuce.pool.max-wait=-1\r\nspring.redis.lettuce.pool.max-idle=5\r\nspring.redis.lettuce.pool.min-idle=0\r\n\r\n#微信支付接口()\r\n# appid\r\nwx.open.app_id=wxed9954c01bb89b47\r\n# appsecret\r\nwx.open.app_secret=a7482517235173ddb4083788de60b90e\r\n# url\r\nwx.open.redirect_url=http://guli.shop/api/ucenter/wx/callback\r\n\r\n#支付宝支付\r\nalipay.APP_ID=\r\nalipay.APP_PRIVATE_KEY=\r\nalipay.ALIPAY_PUBLIC_KEY=\r\nalipay.GATEWAY_URL=\r\n\r\n\r\n#json时间格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#mapper路径\r\nmybatis-plus.mapper-locations=classpath:com/hhz/ucenter/mapper/xml/*.xml\r\n\r\n#mybatis控制台打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl', '8e13bbcf2c551a124343e3de4dc31185', '2023-05-10 11:41:10', '2023-05-10 03:41:10', NULL, '0:0:0:0:0:0:0:1', 'I', '', '');
INSERT INTO `his_config_info` VALUES (0, 34, 'service-vod-dev.properties', 'DEFAULT_GROUP', '', '# vod\r\n#accesskey\r\naliyun.vod.file.keyid=\r\naliyun.vod.file.keysecret=\r\n\r\n# 单个文件最大上传大小\r\nspring.servlet.multipart.max-file-size=1024MB\r\n# 请求数10M\r\nspring.servlet.multipart.max-request-size=1024MB\r\n', 'f8f6a25c9bb075f3d4105199df46b6b4', '2023-05-10 11:41:32', '2023-05-10 03:41:33', NULL, '0:0:0:0:0:0:0:1', 'I', '', '');
INSERT INTO `his_config_info` VALUES (0, 35, 'service-acl-dev.properties', 'DEFAULT_GROUP', '', '# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#json日期格式\r\nspring.jackson.date-format=yyyy-MM-dd HH:mm:ss\r\nspring.jackson.time-zone=GMT+8\r\n\r\n#Redis使用Linux配置的ip\r\nspring.redis.host=127.0.0.1\r\nspring.redis.port=6379\r\nspring.redis.database= 0\r\nspring.redis.timeout=1800000\r\n#redis配置\r\nspring.redis.lettuce.pool.max-active=20\r\nspring.redis.lettuce.pool.max-wait=-1\r\nspring.redis.lettuce.pool.max-idle=5\r\nspring.redis.lettuce.pool.min-idle=0\r\n\r\n#mapper路径\r\nmybatis-plus.mapper-locations=classpath:com/hhz/serviceacl/mapper/xml/*.xml\r\n\r\n#mybatis配置控制台打印格式\r\nmybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl', 'f680ecd1e119724c62587319a2589670', '2023-05-10 11:42:01', '2023-05-10 03:42:02', NULL, '0:0:0:0:0:0:0:1', 'I', '', '');
INSERT INTO `his_config_info` VALUES (20, 36, 'service-oss-dev.properties', 'DEFAULT_GROUP', '', '#阿里云 OSS\r\n#oss配置\r\naliyun.oss.file.endpoint=oss-cn-hongkong.aliyuncs.com\r\naliyun.oss.file.keyid=\r\naliyun.oss.file.keysecret=\r\n#bucket名\r\naliyun.oss.file.bucketname=yuhaiedu\r\n', 'e0b1ee8a69539b8dabf55275e0c296e5', '2023-05-10 13:02:14', '2023-05-10 05:02:14', 'nacos', '0:0:0:0:0:0:0:1', 'U', '', '');
INSERT INTO `his_config_info` VALUES (23, 37, 'service-vod-dev.properties', 'DEFAULT_GROUP', '', '# vod\r\n#accesskey\r\naliyun.vod.file.keyid=\r\naliyun.vod.file.keysecret=\r\n\r\n# 单个文件最大上传大小\r\nspring.servlet.multipart.max-file-size=1024MB\r\n# 请求数10M\r\nspring.servlet.multipart.max-request-size=1024MB\r\n', 'f8f6a25c9bb075f3d4105199df46b6b4', '2023-05-10 13:04:33', '2023-05-10 05:04:34', 'nacos', '0:0:0:0:0:0:0:1', 'U', '', '');
INSERT INTO `his_config_info` VALUES (20, 38, 'service-oss-dev.properties', 'DEFAULT_GROUP', '', '#阿里云 OSS\n#oss配置\naliyun.oss.file.endpoint=oss-cn-hongkong.aliyuncs.com\naliyun.oss.file.keyid=LTAI5tK5JkFaffQhZ2TZT5D8\naliyun.oss.file.keysecret=XzzWyEXkbOnOGfmfhYiEbYofdxHwZ5\n#bucket名\naliyun.oss.file.bucketname=yuhaiedu', '59e68b046cfb18be2b096e642c69bc22', '2023-05-10 13:57:43', '2023-05-10 05:57:43', 'nacos', '0:0:0:0:0:0:0:1', 'U', '', '');
INSERT INTO `his_config_info` VALUES (20, 39, 'service-oss-dev.properties', 'DEFAULT_GROUP', '', '#阿里云 OSS\n#oss配置\n#aliyun.oss.file.endpoint=oss-cn-hongkong.aliyuncs.com\n#aliyun.oss.file.keyid=LTAI5tK5JkFaffQhZ2TZT5D8\n#aliyun.oss.file.keysecret=XzzWyEXkbOnOGfmfhYiEbYofdxHwZ5\n#bucket名\n#aliyun.oss.file.bucketname=yuhaiedu', '4c09e9dd5ea18d5978c1fcea130d172a', '2023-05-10 14:04:26', '2023-05-10 06:04:26', 'nacos', '0:0:0:0:0:0:0:1', 'U', '', '');
INSERT INTO `his_config_info` VALUES (0, 40, 'canal-client-dev.properties', 'DEFAULT_GROUP', '', '# mysql配置\r\nspring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver\r\nspring.datasource.url=jdbc:mysql://localhost:3306/yunhaiedu?serverTimezone=GMT%2B8\r\nspring.datasource.username=root\r\nspring.datasource.password=123456\r\n\r\n#canal 服务地址\r\ncanalClient.host=127.0.0.1\r\ncanalClient.port=11111\r\ncanalClient.destination=example\r\ncanalClient.username=\r\ncanalClient.password=\r\ncanalClient.batchsize=1000\r\n\r\n\r\n# es 服务地址\r\nspring.elasticsearch.rest.uris=http://localhost:9200\r\nspring.elasticsearch.rest.username=\r\nspring.elasticsearch.rest.password=', '50b0456963173fd193a10d0d283e66f9', '2023-05-10 14:05:26', '2023-05-10 06:05:27', NULL, '0:0:0:0:0:0:0:1', 'I', '', '');
INSERT INTO `his_config_info` VALUES (20, 41, 'service-oss-dev.properties', 'DEFAULT_GROUP', '', '#阿里云 OSS\n#oss配置\naliyun.oss.file.endpoint=oss-cn-hongkong.aliyuncs.com\naliyun.oss.file.keyid=LTAI5tK5JkFaffQhZ2TZT5D8\naliyun.oss.file.keysecret=XzzWyEXkbOnOGfmfhYiEbYofdxHwZ5\n#bucket名\naliyun.oss.file.bucketname=yuhaiedu', '59e68b046cfb18be2b096e642c69bc22', '2023-05-10 14:25:57', '2023-05-10 06:25:58', 'nacos', '0:0:0:0:0:0:0:1', 'U', '', '');
INSERT INTO `his_config_info` VALUES (23, 42, 'service-vod-dev.properties', 'DEFAULT_GROUP', '', '# vod\n#accesskey\naliyun.vod.file.keyid=LTAI5tK5JkFaffQhZ2TZT5D8\naliyun.vod.file.keysecret=XzzWyEXkbOnOGfmfhYiEbYofdxHwZ5\n\n# 单个文件最大上传大小\nspring.servlet.multipart.max-file-size=1024MB\n# 请求数10M\nspring.servlet.multipart.max-request-size=1024MB\n', '8955c6d38d5e1ef8106cc53dbbd327a9', '2023-05-10 14:26:30', '2023-05-10 06:26:31', 'nacos', '0:0:0:0:0:0:0:1', 'U', '', '');

-- ----------------------------
-- Table structure for permissions
-- ----------------------------
DROP TABLE IF EXISTS `permissions`;
CREATE TABLE `permissions`  (
  `role` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `resource` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `action` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  UNIQUE INDEX `uk_role_permission`(`role`, `resource`, `action`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of permissions
-- ----------------------------

-- ----------------------------
-- Table structure for roles
-- ----------------------------
DROP TABLE IF EXISTS `roles`;
CREATE TABLE `roles`  (
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `role` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  UNIQUE INDEX `idx_user_role`(`username`, `role`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of roles
-- ----------------------------
INSERT INTO `roles` VALUES ('nacos', 'ROLE_ADMIN');

-- ----------------------------
-- Table structure for tenant_capacity
-- ----------------------------
DROP TABLE IF EXISTS `tenant_capacity`;
CREATE TABLE `tenant_capacity`  (
  `id` bigint(0) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT 'Tenant ID',
  `quota` int(0) UNSIGNED NOT NULL DEFAULT 0 COMMENT '配额，0表示使用默认值',
  `usage` int(0) UNSIGNED NOT NULL DEFAULT 0 COMMENT '使用量',
  `max_size` int(0) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个配置大小上限，单位为字节，0表示使用默认值',
  `max_aggr_count` int(0) UNSIGNED NOT NULL DEFAULT 0 COMMENT '聚合子配置最大个数',
  `max_aggr_size` int(0) UNSIGNED NOT NULL DEFAULT 0 COMMENT '单个聚合数据的子配置大小上限，单位为字节，0表示使用默认值',
  `max_history_count` int(0) UNSIGNED NOT NULL DEFAULT 0 COMMENT '最大变更历史数量',
  `gmt_create` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  `gmt_modified` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = '租户容量信息表' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tenant_capacity
-- ----------------------------

-- ----------------------------
-- Table structure for tenant_info
-- ----------------------------
DROP TABLE IF EXISTS `tenant_info`;
CREATE TABLE `tenant_info`  (
  `id` bigint(0) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `kp` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT 'kp',
  `tenant_id` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_id',
  `tenant_name` varchar(128) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT '' COMMENT 'tenant_name',
  `tenant_desc` varchar(256) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'tenant_desc',
  `create_source` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT 'create_source',
  `gmt_create` bigint(0) NOT NULL COMMENT '创建时间',
  `gmt_modified` bigint(0) NOT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE INDEX `uk_tenant_info_kptenantid`(`kp`, `tenant_id`) USING BTREE,
  INDEX `idx_tenant_id`(`tenant_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1 CHARACTER SET = utf8 COLLATE = utf8_bin COMMENT = 'tenant_info' ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of tenant_info
-- ----------------------------

-- ----------------------------
-- Table structure for users
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users`  (
  `username` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `password` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `enabled` tinyint(1) NOT NULL,
  PRIMARY KEY (`username`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of users
-- ----------------------------
INSERT INTO `users` VALUES ('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', 1);

SET FOREIGN_KEY_CHECKS = 1;
